[nike_gangnam_kakao]
title = "나이키 강남 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_xclMzK"
entrySelector = "ul.list_news li"
titleSelector = "span.txt_g"
linkSelector = "a.link_item"
imageSelector = "span.thume_item"
waitUntil = "networkidle"

[nike_seoul_kakao]
title = "나이키 서울 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_iyabK"
entrySelector = "ul.list_news li"
titleSelector = "span.txt_g"
linkSelector = "a.link_item"
imageSelector = "span.thume_item"
waitUntil = "networkidle"
